# ADD instruction Dockerfile for Docker Quick Start
FROM alpine:latest
LABEL maintainer="Sangam Biradar "
LABEL version=2.0
WORKDIR theqsg
ADD --chown=35:35 app-folder.tar special-files/
WORKDIR /
CMD ["sh"]
