# hello-world Dockerfile
FROM scratch
LABEL maintainer="sangam biradar"
LABEL "description"="My development Ubuntu image"
LABEL version="1.0"
LABEL label1="value1" \
   label2="value2" \
   lable3="value3"
LABEL my-multi-line-label="Labels can span \
more than one line in a Dockerfile."
LABEL support-email="support@mycompany.com" support-phone="(123) 456-7890"
LABEL version="2.0"
COPY hello /
CMD ["/hello"]
